[package]
name = "tests"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[dependencies]
anchor-spl = { workspace = true }
anchor-client = { version = "0.31.0", features = ["async"] }
spl-token = { workspace = true }
spl-associated-token-account = { workspace = true }
sha2 = "=0.10.8"
tokio = "1.44.2"
tokens = { version = "0.1.0", path = "../programs/tokens" }
