[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
tokens = "5HYopUu3aUZ3CQC9AMq3iKa5Q9awF6aEm18jvHfKQ45r"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[test]
startup_wait = 10000

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[test.validator]
url = "https://api.mainnet-beta.solana.com"       # This is the url of the cluster that accounts are cloned from (See `test.validator.clone`).
# warp_slot = 1337                                # Warp the ledger to `warp_slot` after starting the validator.
# slots_per_epoch = "5"                           # Override the number of slots in an epoch.
# rpc_port = 1337                                 # Set JSON RPC on this port, and the next port for the RPC websocket.
# limit_ledger_size = "1337"                      # Keep this amount of shreds in root slots.
# ledger = "test-ledger"                          # Set ledger location.
# gossip_port = 1337                              # Gossip port number for the validator.
# gossip_host = "127.0.0.1"                       # Gossip DNS name or IP address for the validator to advertise in gossip.
# faucet_sol = "1337"                             # Give the faucet address this much SOL in genesis.
# faucet_port = 1337                              # Enable the faucet on this port.
# dynamic_port_range = "1337 - 13337"             # Range to use for dynamically assigned ports.
# bind_address = "0.0.0.0"                        # IP address to bind the validator ports.
